#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
#
# Source0 file verified with key 0xD7574483BB57B18D (jr@jriddell.org)
#
Name     : oxygen-sounds
Version  : 5.27.8
Release  : 1
URL      : https://download.kde.org/stable/plasma/5.27.8/oxygen-sounds-5.27.8.tar.xz
Source0  : https://download.kde.org/stable/plasma/5.27.8/oxygen-sounds-5.27.8.tar.xz
Source1  : https://download.kde.org/stable/plasma/5.27.8/oxygen-sounds-5.27.8.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC0-1.0 LGPL-3.0
Requires: oxygen-sounds-data = %{version}-%{release}
Requires: oxygen-sounds-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package data
Summary: data components for the oxygen-sounds package.
Group: Data

%description data
data components for the oxygen-sounds package.


%package license
Summary: license components for the oxygen-sounds package.
Group: Default

%description license
license components for the oxygen-sounds package.


%prep
%setup -q -n oxygen-sounds-5.27.8
cd %{_builddir}/oxygen-sounds-5.27.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1695052601
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1695052601
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/oxygen-sounds
cp %{_builddir}/oxygen-sounds-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/oxygen-sounds/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/oxygen-sounds-%{version}/LICENSES/LGPL-3.0-or-later.txt %{buildroot}/usr/share/package-licenses/oxygen-sounds/f45ee1c765646813b442ca58de72e20a64a7ddba || :
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/sounds/Oxygen-Im-Cant-Connect.ogg
/usr/share/sounds/Oxygen-Im-Connection-Lost.ogg
/usr/share/sounds/Oxygen-Im-Contact-In.ogg
/usr/share/sounds/Oxygen-Im-Contact-Out.ogg
/usr/share/sounds/Oxygen-Im-Error-On-Connection.ogg
/usr/share/sounds/Oxygen-Im-Highlight-Msg.ogg
/usr/share/sounds/Oxygen-Im-Internal-Error.ogg
/usr/share/sounds/Oxygen-Im-Irc-Event.ogg
/usr/share/sounds/Oxygen-Im-Low-Priority-Message.ogg
/usr/share/sounds/Oxygen-Im-Message-In.ogg
/usr/share/sounds/Oxygen-Im-Message-Out.ogg
/usr/share/sounds/Oxygen-Im-Network-Problems.ogg
/usr/share/sounds/Oxygen-Im-New-Mail.ogg
/usr/share/sounds/Oxygen-Im-Nudge.ogg
/usr/share/sounds/Oxygen-Im-Phone-Ring.ogg
/usr/share/sounds/Oxygen-Im-Sms.ogg
/usr/share/sounds/Oxygen-Im-User-Auth.ogg
/usr/share/sounds/Oxygen-K3B-Finish-Error.ogg
/usr/share/sounds/Oxygen-K3B-Finish-Success.ogg
/usr/share/sounds/Oxygen-K3B-Insert-Medium.ogg
/usr/share/sounds/Oxygen-Sys-App-Error-Critical.ogg
/usr/share/sounds/Oxygen-Sys-App-Error-Serious-Very.ogg
/usr/share/sounds/Oxygen-Sys-App-Error-Serious.ogg
/usr/share/sounds/Oxygen-Sys-App-Error.ogg
/usr/share/sounds/Oxygen-Sys-App-Message.ogg
/usr/share/sounds/Oxygen-Sys-App-Negative.ogg
/usr/share/sounds/Oxygen-Sys-App-Positive.ogg
/usr/share/sounds/Oxygen-Sys-Error-Printing.ogg
/usr/share/sounds/Oxygen-Sys-File-Open-Foes.ogg
/usr/share/sounds/Oxygen-Sys-List-End.ogg
/usr/share/sounds/Oxygen-Sys-List-Match-Multiple.ogg
/usr/share/sounds/Oxygen-Sys-List-Match-No.ogg
/usr/share/sounds/Oxygen-Sys-Log-In-Long.ogg
/usr/share/sounds/Oxygen-Sys-Log-In-Short.ogg
/usr/share/sounds/Oxygen-Sys-Log-In.ogg
/usr/share/sounds/Oxygen-Sys-Log-Out-Long.ogg
/usr/share/sounds/Oxygen-Sys-Log-Out.ogg
/usr/share/sounds/Oxygen-Sys-Question.ogg
/usr/share/sounds/Oxygen-Sys-Special.ogg
/usr/share/sounds/Oxygen-Sys-Trash-Emptied.ogg
/usr/share/sounds/Oxygen-Sys-Warning.ogg
/usr/share/sounds/Oxygen-Window-All-Desktops-Not.ogg
/usr/share/sounds/Oxygen-Window-All-Desktops.ogg
/usr/share/sounds/Oxygen-Window-Close.ogg
/usr/share/sounds/Oxygen-Window-Maximize.ogg
/usr/share/sounds/Oxygen-Window-Minimize.ogg
/usr/share/sounds/Oxygen-Window-Move-Stop.ogg
/usr/share/sounds/Oxygen-Window-Move.ogg
/usr/share/sounds/Oxygen-Window-Shade-Down.ogg
/usr/share/sounds/Oxygen-Window-Shade-Up.ogg

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/oxygen-sounds/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/oxygen-sounds/f45ee1c765646813b442ca58de72e20a64a7ddba
